### ISSUE TITLE
Dante + stack --docker needs documentation

### ISSUE THREAD

**Issue by aspiwack** [jyp/dante#80]
In order to use Dante together with `stack --docker`, one apparently needs to mount the `/tmp/` directory from the host into the docker image. Which can be done by setting the following in one's `stack.yaml`

```yaml
docker:
  enable: true
  mount:
          - /tmp:/tmp 
```

Maybe this won't be necessary if #78 ends up removing the temp files altogether.
